version: '3'

networks:
  front:
    driver: bridge
  back:
    driver: bridge

volumes:
  postgres-data:
    driver: local

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9299"
    networks:
      - back
      - front

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - back