version: '3'

volumes:
  postgres-data:
    driver: local

services:
  app:
    build: .
    command: npm run run
    volumes:
      - .:/app:z
    depends_on:
      - postgres
    links:
      - postgres:postgres
    ports:
      - "3000:3000"
      - "9229:9299"
    environment:
      - SERVER_PORT=3000
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  phppgadmin:
      # fixed fork of jacksoncage/phppgadmin
      image: dockage/phppgadmin
      ports:
          - "${PHP_PG_ADMIN_PORT}:80"
      environment:
          - PHP_PG_ADMIN_SERVER_HOST=postgres
          - PHP_PG_ADMIN_SERVER_PORT=${DATABASE_PORT}
          - PHP_PG_ADMIN_SERVER_DEFAULT_DB=${DATABASE_NAME}
      links:
          - postgres:postgres