version: '3'

networks:
  front:
    driver: bridge
  back:
    driver: bridge

volumes:
  postgres-data:
    driver: local

services:
  app:
    build: .
    command: npm run run
    volumes:
      - .:/app:z
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "9229:9299"
    links:
      - db:postgres
    networks:
      - back
      - front
    environment:
      - POSTGRES_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db/${DATABASE_NAME}

  db:
      image: postgres
      volumes:
          - ${DATABASE_DATA_DIR}:/var/lib/postgresql/data
          - ${DATABASE_LOG_DIR}:/var/log/postgresql
      ports:
          - "${DATABASE_PORT}:5432"
      environment:
          - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
          - POSTGRES_USER=${DATABASE_USER}
          - POSTGRES_DB=${DATABASE_NAME}
          - PGDATA=/var/lib/postgresql/data/pgdata

  phppgadmin:
      # fixed fork of jacksoncage/phppgadmin
      image: dockage/phppgadmin
      ports:
          - "${PHP_PG_ADMIN_PORT}:80"
      environment:
          - PHP_PG_ADMIN_SERVER_HOST=db
          - PHP_PG_ADMIN_SERVER_PORT=${DATABASE_PORT}
          - PHP_PG_ADMIN_SERVER_DEFAULT_DB=${DATABASE_NAME}
      links:
          - db:postgres